import axiosInstance from "./axiosInstance";

export { axiosInstance };

// Central API endpoints registry
export const ENDPOINTS = {
  auth: {
    login: "/api/auth/login",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
  },
  superAdmin: {
    companies: "/api/super-admin/companies",
    companyStatus: (id: string) => `/api/super-admin/companies/${id}/status`,
    systemPlans: "/api/super-admin/system-plans",
    systemPlan: (id: string) => `/api/super-admin/system-plans/${id}`,
    auditLogs: "/api/super-admin/audit-logs",
    globalConfig: "/api/super-admin/global-config",
  },
  clientAdmin: {
    agents: "/api/client-admin/agents",
    agentActive: (id: string) => `/api/client-admin/agents/${id}/active`,
    agentDelete: (id: string) => `/api/client-admin/agents/${id}`,
    routingPolicy: "/api/client-admin/routing-policy",
    pairingCode: "/api/client-admin/whatsapp/pairing-code",
    verifyWhatsapp: "/api/client-admin/whatsapp/verify",
    metaForms: "/api/client-admin/meta-forms",
    verifySMTP: "/api/client-admin/smtp/verify",
    billingQuotas: "/api/client-admin/billing/quotas",
    billingInvoices: "/api/client-admin/billing/invoices",
    automationRules: "/api/client-admin/automation-rules",
    ruleStatus: (id: string) => `/api/client-admin/automation-rules/${id}/status`,
    ruleDelete: (id: string) => `/api/client-admin/automation-rules/${id}`,
  },
  leads: {
    base: "/api/leads",
    createPublic: "/api/leads/create",
    status: (id: string) => `/api/leads/${id}/status`,
    notes: (id: string) => `/api/leads/${id}/notes`,
    followUp: (id: string) => `/api/leads/${id}/followup`,
  },
  chat: {
    conversations: "/api/conversations",
    messages: (leadId: string) => `/api/conversations/${leadId}/messages`,
    autoReply: (leadId: string) => `/api/conversations/${leadId}/auto-reply`,
  },
  appointments: {
    base: "/api/appointments",
    cancel: (id: string) => `/api/appointments/${id}/cancel`,
    confirm: (id: string) => `/api/appointments/${id}/confirm`,
    publicSlots: (companyId: string, date: string) => `/api/public/appointments/slots?companyId=${companyId}&date=${date}`,
    publicBook: "/api/public/appointments",
    publicMeta: (companyId: string) => `/api/public/appointments/meta?companyId=${companyId}`,
    slotConfigs: "/api/client-admin/appointments/slot-configs",
    slotConfigDelete: (id: string) => `/api/client-admin/appointments/slot-configs/${id}`,
    serviceConfigs: "/api/client-admin/appointments/service-configs",
    serviceConfigDelete: (id: string) => `/api/client-admin/appointments/service-configs/${id}`,
  },
  knowledge: {
    faqs: "/api/knowledge/faqs",
    faqDelete: (id: string) => `/api/knowledge/faqs/${id}`,
    documents: "/api/knowledge/documents",
    documentUpload: "/api/knowledge/documents/upload",
    aiSettings: "/api/knowledge/ai-settings",
    whatsappTemplates: "/api/knowledge/whatsapp-templates",
    templateDelete: (id: string) => `/api/knowledge/whatsapp-templates/${id}`,
  },
  webhook: {
    aiChat: "/api/ai/chat",
    whatsapp: "/api/webhooks/whatsapp",
    facebookLeads: "/api/webhooks/facebook-leads",
  },
  whatsapp: {
    contacts: "/api/client-admin/whatsapp/contacts",
    contactDetail: (id: string) => `/api/client-admin/whatsapp/contacts/${id}`,
    contactTags: "/api/client-admin/whatsapp/contacts/tags",
    contactExport: "/api/client-admin/whatsapp/contacts/export",
    contactBulkDelete: "/api/client-admin/whatsapp/contacts/bulk-delete",
    contactBulkTag: "/api/client-admin/whatsapp/contacts/bulk-tag",
    contactImport: "/api/client-admin/whatsapp/contacts/import",
    groups: "/api/client-admin/whatsapp/groups",
    groupDetail: (id: string) => `/api/client-admin/whatsapp/groups/${id}`,
    groupAssign: (id: string) => `/api/client-admin/whatsapp/groups/${id}/assign`,
    groupRemove: (id: string) => `/api/client-admin/whatsapp/groups/${id}/remove`,
    campaigns: "/api/client-admin/whatsapp/campaigns",
    campaignDetail: (id: string) => `/api/client-admin/whatsapp/campaigns/${id}`,
    campaignDuplicate: (id: string) => `/api/client-admin/whatsapp/campaigns/${id}/duplicate`,
    campaignSend: (id: string) => `/api/client-admin/whatsapp/campaigns/${id}/send`,
    campaignCancel: (id: string) => `/api/client-admin/whatsapp/campaigns/${id}/cancel`,
    campaignPause: (id: string) => `/api/client-admin/whatsapp/campaigns/${id}/pause`,
    scheduled: "/api/client-admin/whatsapp/scheduled",
    reportsDashboard: "/api/client-admin/whatsapp/reports/dashboard",
    reportsCampaigns: "/api/client-admin/whatsapp/reports/campaigns",
    reportsTrends: "/api/client-admin/whatsapp/reports/trends",
    reportsRecent: "/api/client-admin/whatsapp/reports/recent",
    settings: "/api/client-admin/whatsapp/settings",
    settingsConnect: "/api/client-admin/whatsapp/settings/connect",
    settingsDisconnect: "/api/client-admin/whatsapp/settings/disconnect",
    apiKeys: "/api/client-admin/whatsapp/api-keys",
    apiKeysRegenerate: "/api/client-admin/whatsapp/api-keys/regenerate",
    billing: "/api/client-admin/whatsapp/billing",
  },
  superAdminWhatsapp: {
    stats: "/api/super-admin/whatsapp/stats",
    tenants: "/api/super-admin/whatsapp/tenants",
    queue: "/api/super-admin/whatsapp/queue",
    campaigns: "/api/super-admin/whatsapp/campaigns",
    suspendCampaign: (id: string) => `/api/super-admin/whatsapp/campaigns/${id}/suspend`,
    restrictTenant: (id: string) => `/api/super-admin/whatsapp/tenants/${id}/restrict`,
  },
};

export default axiosInstance;
